# Generated by Django 5.1.2 on 2024-10-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='is_verified',
            new_name='is_verified_tac',
        ),
    ]
