# Generated by Django 5.1.2 on 2024-10-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_is_verified_clients_is_verified_tac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Client_id',
            new_name='client_id',
        ),
    ]
