# Generated by Django 5.1.2 on 2024-10-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_client_id_clients_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='otp',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
